services:
  aoba-telegram-bot:
    build: .
    container_name: aoba-telegram-bot
    restart: always
    environment:
      - NODE_ENV=production
      - AOBA_BOT_TOKEN=${AOBA_BOT_TOKEN}
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command: --interval 60 --cleanup "aoba-telegram-bot"
